---
# this is a config file for the github action labeler

# Add 'label1' to any changes within 'example' folder or any subfolders
example_change:
  - example/**

# Add 'label2' to any file changes within 'example2' folder
example2_change: example2/*

# Add label3 to any change to .txt files within the entire repository.
# Quotation marks are required for the leading asterisk
text_files:
  - '**/*.txt'
