[package]
name = "bitcoin_replay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
num-bigint = "0.4.0"
num-traits = "0.2.14"
leveldb = "0.8.6"