IMAGE_ENRICHMENT_PROMPT = (
    "Create a concise and effective image generation prompt within"
    " 400 characters or less, "
    "based on Stable Diffusion and Dalle best practices. Starting"
    " prompt: \n\n'"
    # f"{prompt}'\n\n"
    "Improve the prompt with any applicable details or keywords by"
    " considering the following aspects: \n"
    "1. Subject details (like actions, emotions, environment) \n"
    "2. Artistic style (such as surrealism, hyperrealism) \n"
    "3. Medium (digital painting, oil on canvas) \n"
    "4. Color themes and lighting (like warm colors, cinematic"
    " lighting) \n"
    "5. Composition and framing (close-up, wide-angle) \n"
    "6. Additional elements (like a specific type of background,"
    " weather conditions) \n"
    "7. Any other artistic or thematic details that can make the"
    " image more vivid and compelling."
)
