from typing import List

from pydantic import BaseModel, Field


class HierarchicalOrder(BaseModel):
    """
    Represents a single task assignment within the hierarchical swarm.

    This class defines the structure for individual task orders that the director
    distributes to worker agents. Each order specifies which agent should execute
    what specific task.

    Attributes:
        agent_name (str): The name of the agent assigned to execute the task. Must match an existing agent in the swarm.
        task (str): The specific task description to be executed by the assigned agent. Should be clear and actionable.
    """

    agent_name: str = Field(
        ...,
        description="Specifies the name of the agent to which the task is assigned. This is a crucial element in the hierarchical structure of the swarm, as it determines the specific agent responsible for the task execution.",
    )
    task: str = Field(
        ...,
        description="Defines the specific task to be executed by the assigned agent. This task is a key component of the swarm's plan and is essential for achieving the swarm's goals.",
    )


class HierarchicalOrderRearrange(BaseModel):
    """
    Represents a rearrangement specification for task assignments within the hierarchical swarm.

    This class defines the structure for rearranging how tasks are assigned and managed through the initial task and flow of communication between agents.

    Attributes:
        initial_task (str): The initial task that the director has to execute.
        flow_of_communication (str): How the agents will communicate with each other to accomplish the task. Can use arrows (->) and commas to denote sequential and parallel communication.
    """

    initial_task: str = Field(
        ...,
        description="The initial task that the director has to execute.",
    )
    flow_of_communication: str = Field(
        ...,
        description="How the agents will communicate with each other to accomplish the task. \
                      Example: agent_one -> agent_two -> agent_three -> agent_four -> agent_one, \
                      can use arrows (->) for sequential communication and commas for parallel communication. \
                      For example: agent_one -> agent_two, agent_three -> agent_four means agent_one passes to agent_two and agent_three passes to agent_four in parallel.",
    )


class OrderBatch(BaseModel):
    """Defines the task assignments emitted by a hierarchical director.

    Attributes:
        orders: Task assignments to dispatch to worker agents.
    """

    orders: List[HierarchicalOrder] = Field(
        ...,
        description="Task assignments for the worker agents.",
    )


class SwarmSpec(BaseModel):
    """
    Defines the complete specification for a hierarchical swarm execution.

    This class contains the overall plan and all individual orders that the director
    creates to coordinate the swarm's activities. It serves as the structured output
    format for the director agent.

    Attributes:
        plan (str): A comprehensive plan outlining the sequence of actions and strategy for the entire swarm to accomplish the given task.
        orders (List[HierarchicalOrder]): A list of specific task assignments to individual agents within the swarm.
    """

    plan: str = Field(
        ...,
        description="A comprehensive plan generated by the director agent for the swarm to accomplish the given task. The director autonomously reasons through the problem, devises its own strategy, and determines the sequence of actions. \
This plan reflects the director's independent thought process, outlining the rationale, priorities, and steps it deems necessary for successful execution. \
It serves as a blueprint for the swarm, enabling agents to follow the director's self-derived guidance and adapt as needed throughout the process.",
    )

    orders: List[HierarchicalOrder] = Field(
        ...,
        description="A collection of task assignments to specific agents within the swarm. These orders are the specific instructions that guide the agents in their task execution and are a key element in the swarm's plan.",
    )


class AgentScore(BaseModel):
    """
    Holds the score and feedback for an agent's performance as judged in the swarm process.

    Attributes:
        agent_name (str): The name of the agent being scored.
        score (int): The numerical score (0-10) given to the agent for its performance.
        reasoning (str): The reasoning or justification for the score assigned.
        suggestions (str): Suggestions or feedback for improvement for the agent.
    """

    agent_name: str = Field(
        ..., description="The name of the agent being evaluated."
    )
    score: int = Field(
        ...,
        ge=0,
        le=10,
        description="The score for the agent's performance, from 0 (worst) to 10 (best).",
    )
    reasoning: str = Field(
        ...,
        description="The reasoning or justification for the assigned score.",
    )
    suggestions: str = Field(
        ...,
        description="Suggestions or feedback for improvement for the agent.",
    )


class JudgeReport(BaseModel):
    """
    Summarizes the overall results of the judging/evaluation process within the hierarchical swarm.

    Attributes:
        overall_quality (int): Overall quality score (0-10) for the swarm's collective performance.
        scores (List[AgentScore]): List of individual agent scores and feedback.
        summary (str): A summary of the evaluation findings and key points.
    """

    overall_quality: int = Field(
        ...,
        ge=0,
        le=10,
        description="Overall quality score (0-10) for the swarm's collective output or performance.",
    )
    scores: List[AgentScore] = Field(
        ...,
        description="A list of AgentScore items, each holding detailed feedback and scores for individual agents.",
    )
    summary: str = Field(
        ...,
        description="A narrative summary of the evaluation findings and key points.",
    )
